README.md
workers/frinx_rest.py

Makes odl base url configurable throught env variable

Add configurable odl url

---

workers/cli_worker.py
workers/cli_worker_test.py
workers/frinx_rest.py
workers/netconf_worker.py
workers/netconf_worker_test.py
workers/standalone_main.py
workers/uniconfig_worker.py
workers/uniconfig_worker_test.py
workers/worker_wrapper.py

Set according to env var ?
Basic tls support no cert checking

Add tls support for uniconfig

---

Dockerfile
workers/main.py
workflows/Mount_apply_template_unmount_cli.json

- entrypoint introduced so micros will start automatically
- fixed unmount in workflow
Signed-off-by: Martin Sunal <msunal@frinx.io>

Fixed startup and workflow

---

Dockerfile
workers/import_workflows.py

- fixed logging
- small change in docker file
Signed-off-by: Martin Sunal <msunal@frinx.io>

Fixed logging in WF import

---

.gitignore
workers/cli_worker.py
workers/cli_worker_test.py

Default value is 'tree-parser'.
Signed-off-by: Martin Sunal <msunal@frinx.io>

Add configurable 'parsing-engine' option

---

workers/cli_worker.py
workers/netconf_worker.py

- added array to node in mount requests
Signed-off-by: Martin Sunal <msunal@frinx.io>

fixed mount requests

---

conductor-client/python/conductor/ConductorWorker.py
conductor-client/python/conductor/conductor.py
workers/main.py
workers/worker_wrapper.py

Signed-off-by: Maros Marsalek <mmarsalek@frinx.io>
Describe the changes made in this PR.

FM-579 Add headers required by wf-proxy to all requests

---

workers/cli_worker.py

Added execute task to be used in future workflows
Signed-off-by: Matej Matkuliak mmatkuliak@frinx.io

Added execute task definition to cli_worker

---

frinx_conductor_workers/cli_worker.py
frinx_conductor_workers/cli_worker_test.py
frinx_conductor_workers/http_worker.py
frinx_conductor_workers/import_workflows.py
frinx_conductor_workers/netconf_worker.py
frinx_conductor_workers/netconf_worker_test.py
frinx_conductor_workers/uniconfig_worker.py
frinx_conductor_workers/uniconfig_worker_test.py
main.py
setup.py
workflows/Mount_apply_template_unmount_cli.json

Describe the changes made in this PR.

Update workers for Uniconfig 4.2.7

---

frinx_conductor_workers/http_worker.py

Signed-off-by: Tomas <thodor@frinx.io>
Describe the changes made in this PR.

Fix http task body

---

frinx_conductor_workers/connection_manager_worker.py

Connection manager worker for installation multiple devices in parallel by one request

Add connection manager worker for installing multiple nodes in parallel

---

frinx_conductor_workflows/Mount_apply_template_unmount_cli.json
setup.py

Describe the changes made in this PR.

Update workfow description

---

frinx_conductor_workers/frinx_conductor_workers/resource_manager_worker.py
frinx_conductor_workers/frinx_conductor_workers/util.py
frinx_conductor_workers/setup.py

Rewrite imports for fm-base classes

Rewrite imports for fm-base classes

---

frinx_conductor_workers/frinx_conductor_workers/resource_manager_worker.py
frinx_conductor_workers/frinx_conductor_workers/util.py
frinx_conductor_workers/frinx_conductor_workflows/resource_manager_workflows/Allocate_IPv4_Prefix_Resource.json
frinx_conductor_workers/frinx_conductor_workflows/resource_manager_workflows/Allocate_IPv4_Resource.json
frinx_conductor_workers/frinx_conductor_workflows/resource_manager_workflows/Allocate_IPv6_Prefix_Resource.json
frinx_conductor_workers/frinx_conductor_workflows/resource_manager_workflows/Allocate_IPv6_Resource.json
frinx_conductor_workers/frinx_conductor_workflows/resource_manager_workflows/Create_IPv4_Pool.json
frinx_conductor_workers/frinx_conductor_workflows/resource_manager_workflows/Create_IPv4_Prefix_Pool.json
frinx_conductor_workers/frinx_conductor_workflows/resource_manager_workflows/Create_IPv6_Pool.json
frinx_conductor_workers/frinx_conductor_workflows/resource_manager_workflows/Create_IPv6_Prefix_Pool.json
frinx_conductor_workers/frinx_conductor_workflows/resource_manager_workflows/Deallocate_Resource.json
frinx_conductor_workers/frinx_conductor_workflows/resource_manager_workflows/Delete_Pool_IPv4.json
frinx_conductor_workers/frinx_conductor_workflows/resource_manager_workflows/Delete_Pool_IPv6.json

Refactor of all resource_manager tasks output params, so now every task output will start as "result.data" if task will be completed successfully, if not then task output will be "result.error".
Add new workers and workflows for resource_manager.

Refactor of output params

---

frinx_conductor_workers/frinx_conductor_workers/resource_manager_worker.py
frinx_conductor_workers/setup.py

- version 1.1.8
- add subnet param to worker which calculate desired size from prefix

Add subnet param to desired size calculation

---

frinx_python_sdk/src/frinx/common/frinx_rest.py
frinx_python_sdk/src/frinx/common/import_workflows.py
frinx_python_sdk/src/frinx/common/logging/logging_common.py
frinx_python_sdk/src/frinx/common/util.py
frinx_python_sdk/src/frinx/common/worker/service.py
frinx_python_sdk/src/frinx/common/worker/task.py
frinx_python_sdk/src/frinx/common/worker/worker.py
frinx_python_sdk/src/frinx/common/workflow/service.py
frinx_python_sdk/src/frinx/common/workflow/task.py
frinx_python_sdk/src/frinx/common/workflow/workflow.py
frinx_python_sdk/src/frinx/main.py
frinx_python_sdk/src/frinx/services/http/http_worker.py
frinx_python_sdk/src/frinx/services/inventory/inventory_worker.py
frinx_python_sdk/src/frinx/services/inventory/templates.py
frinx_python_sdk/src/frinx/services/inventory/utils.py
frinx_python_sdk/src/frinx/services/monitoring/influxdb_worker.py
frinx_python_sdk/src/frinx/services/uniconfig/cli_worker.py
frinx_python_sdk/src/frinx/services/uniconfig/netconf_worker.py
frinx_python_sdk/src/frinx/services/uniconfig/uniconfig_worker.py
frinx_python_sdk/src/frinx/workers/monitoring/influxdb_workers.py
frinx_python_sdk/src/frinx/workers/test/test_worker.py
frinx_python_sdk/tests/common/worker/task_def_test.py

snake case formating

---

frinx_python_sdk/setup.py
frinx_python_sdk/src/frinx/services/uniconfig/cli_worker.py

Add optional timeout parameter to execute_and_read_rpc_cli function.

Polish cli_worker.py module

---

frinx_python_sdk/setup.py
frinx_python_sdk/src/frinx/common/worker/task_result.py
frinx_python_sdk/src/frinx/common/worker/worker.py
frinx_python_sdk/src/frinx/services/inventory/utils.py
frinx_python_sdk/src/frinx/workers/http/http_worker.py
frinx_python_sdk/src/frinx/workers/inventory/inventory_worker.py
frinx_python_sdk/src/frinx/workers/monitoring/influxdb_workers.py
frinx_python_sdk/src/frinx/workers/test/test_worker.py
frinx_python_sdk/src/frinx/workers/uniconfig/cli_worker.py
frinx_python_sdk/src/frinx/workers/uniconfig/netconf_worker.py
frinx_python_sdk/src/frinx/workers/uniconfig/uniconfig_worker.py
frinx_python_sdk/tests/common/worker/task_def_test.py
frinx_python_sdk/tests/workers/uniconfig/uniconfig_test.py

- Make status of TaskResult mandatory.
- Parametrize inventory address in graphql client.
- Remove TaskStatus parameter from execute method.

Improvements

---

system_tests/pytest.ini

only python.ini small change
no need

system-tests enable logging into file

---

.github/workflows/run-system-tests.yml

Added new workflow to run conductor system tests

workflow: run-system-tests

---

system_tests/tests/frinx/test_frinx_api.py

Waiting for https://github.com/FRINXio/conductor/pull/133

Add test for new frinx API: path/ family/

---

frinx_conductor_workers/frinx_conductor_workflows/resource_manager_workflows/Allocate_IPv4_Prefix_Resource.json
frinx_conductor_workers/frinx_conductor_workflows/resource_manager_workflows/Allocate_IPv6_Prefix_Resource.json
frinx_conductor_workers/setup.py

Version from 1.1.11 to 1.1.12
- Add subnet param to "calculate_desired_size_from_prefix" task in allocate WFs

Add subnet param to allocate WFs

---

.github/workflows/run-system-tests.yml
frinx_python_sdk/requirements.txt

Fix python package version for pydantic==1.10.7
- [x ] Add description to the PR

Fix python package version for pydantic

---

frinx_conductor_workers/frinx_conductor_workers/resource_manager_worker.py
frinx_conductor_workers/frinx_conductor_workflows/resource_manager_workflows/Allocate_IPv4_Prefix_Resource.json
frinx_conductor_workers/frinx_conductor_workflows/resource_manager_workflows/Allocate_IPv4_Resource.json
frinx_conductor_workers/frinx_conductor_workflows/resource_manager_workflows/Allocate_IPv6_Prefix_Resource.json
frinx_conductor_workers/frinx_conductor_workflows/resource_manager_workflows/Allocate_IPv6_Resource.json
frinx_conductor_workers/frinx_conductor_workflows/resource_manager_workflows/Create_IPv4_Pool.json
frinx_conductor_workers/frinx_conductor_workflows/resource_manager_workflows/Create_IPv4_Prefix_Pool.json
frinx_conductor_workers/frinx_conductor_workflows/resource_manager_workflows/Create_IPv6_Pool.json
frinx_conductor_workers/frinx_conductor_workflows/resource_manager_workflows/Create_IPv6_Prefix_Pool.json
frinx_conductor_workers/frinx_conductor_workflows/resource_manager_workflows/Create_Subnet.json
frinx_conductor_workers/frinx_conductor_workflows/resource_manager_workflows/Deallocate_Resource.json
frinx_conductor_workers/frinx_conductor_workflows/resource_manager_workflows/Delete_Pool_IPv4.json
frinx_conductor_workers/frinx_conductor_workflows/resource_manager_workflows/Delete_Pool_IPv6.json
frinx_conductor_workers/setup.py

Version change from 1.1.12 to 1.1.13

Changes due to changes in RM2.0.0

---

frinx_conductor_workers/frinx_conductor_workers/resource_manager_worker.py
frinx_conductor_workers/frinx_conductor_workflows/resource_manager_workflows/Allocate_IPv4_Prefix_Resource.json
frinx_conductor_workers/frinx_conductor_workflows/resource_manager_workflows/Allocate_IPv4_Resource.json
frinx_conductor_workers/frinx_conductor_workflows/resource_manager_workflows/Allocate_IPv6_Prefix_Resource.json
frinx_conductor_workers/frinx_conductor_workflows/resource_manager_workflows/Allocate_IPv6_Resource.json
frinx_conductor_workers/frinx_conductor_workflows/resource_manager_workflows/Create_IPv4_Pool.json
frinx_conductor_workers/frinx_conductor_workflows/resource_manager_workflows/Create_IPv4_Prefix_Pool.json
frinx_conductor_workers/frinx_conductor_workflows/resource_manager_workflows/Create_IPv6_Pool.json
frinx_conductor_workers/frinx_conductor_workflows/resource_manager_workflows/Create_IPv6_Prefix_Pool.json
frinx_conductor_workers/frinx_conductor_workflows/resource_manager_workflows/Create_Subnet.json
frinx_conductor_workers/frinx_conductor_workflows/resource_manager_workflows/Deallocate_Resource.json
frinx_conductor_workers/frinx_conductor_workflows/resource_manager_workflows/Delete_Pool_IPv4.json
frinx_conductor_workers/frinx_conductor_workflows/resource_manager_workflows/Delete_Pool_IPv6.json
frinx_conductor_workers/setup.py

This reverts commit 22d56d05fd8142c01b05585c1b8f1ff078180176.

Revert "Changes due to changes in RM2.0.0 (#78)"
